export interface Instrument {
    symbol: string
    tickSize: number
    symbolIndex?: number
}

export class InstrumentRepository {
    private _lookup: Map<string,Instrument[]> = new Map()

    constructor() {
        this._lookup.set('FTX',[
            {'symbol': '1INCH-PERP', 'tickSize': 0.0001},
            {'symbol': 'AAVE-PERP', 'tickSize': 0.01},
            {'symbol': 'ADA-PERP', 'tickSize': 5e-06},
            {'symbol': 'AGLD-PERP', 'tickSize': 0.0005},
            {'symbol': 'ALCX-PERP', 'tickSize': 0.1},
            {'symbol': 'ALGO-PERP', 'tickSize': 0.0001},
            {'symbol': 'ALICE-PERP', 'tickSize': 0.0025},
            {'symbol': 'ALPHA-PERP', 'tickSize': 5e-05},
            {'symbol': 'ALT-PERP', 'tickSize': 0.05},
            {'symbol': 'AMPL-PERP', 'tickSize': 0.0001},
            {'symbol': 'ANC-PERP', 'tickSize': 0.00025},
            {'symbol': 'APE-PERP', 'tickSize': 0.0005},
            {'symbol': 'AR-PERP', 'tickSize': 0.001},
            {'symbol': 'ASD-PERP', 'tickSize': 1e-05},
            {'symbol': 'ATLAS-PERP', 'tickSize': 2.5e-07},
            {'symbol': 'ATOM-PERP', 'tickSize': 0.0005},
            {'symbol': 'AUDIO-PERP', 'tickSize': 0.0005},
            {'symbol': 'AVAX-PERP', 'tickSize': 0.001},
            {'symbol': 'AXS-PERP', 'tickSize': 0.001},
            {'symbol': 'BADGER-PERP', 'tickSize': 0.005},
            {'symbol': 'BAL-PERP', 'tickSize': 0.0025},
            {'symbol': 'BAND-PERP', 'tickSize': 0.001},
            {'symbol': 'BAO-PERP', 'tickSize': 2.5e-07},
            {'symbol': 'BAT-PERP', 'tickSize': 2.5e-05},
            {'symbol': 'BCH-PERP', 'tickSize': 0.05},
            {'symbol': 'BIT-PERP', 'tickSize': 0.00025},
            {'symbol': 'BNB-PERP', 'tickSize': 0.0025},
            {'symbol': 'BNT-PERP', 'tickSize': 0.0005},
            {'symbol': 'BOBA-PERP', 'tickSize': 0.0005},
            {'symbol': 'BRZ-PERP', 'tickSize': 1e-05},
            {'symbol': 'BSV-PERP', 'tickSize': 0.01},
            {'symbol': 'BTC-PERP', 'tickSize': 1.0},
            {'symbol': 'BTT-PERP', 'tickSize': 1e-08},
            {'symbol': 'C98-PERP', 'tickSize': 0.0001},
            {'symbol': 'CAKE-PERP', 'tickSize': 0.0025},
            {'symbol': 'CEL-PERP', 'tickSize': 0.0005},
            {'symbol': 'CELO-PERP', 'tickSize': 0.0005},
            {'symbol': 'CHR-PERP', 'tickSize': 5e-05},
            {'symbol': 'CHZ-PERP', 'tickSize': 1e-06},
            {'symbol': 'CLV-PERP', 'tickSize': 0.0005},
            {'symbol': 'COMP-PERP', 'tickSize': 0.01},
            {'symbol': 'CONV-PERP', 'tickSize': 1e-05},
            {'symbol': 'CREAM-PERP', 'tickSize': 0.05},
            {'symbol': 'CRO-PERP', 'tickSize': 2.5e-05},
            {'symbol': 'CRV-PERP', 'tickSize': 5e-05},
            {'symbol': 'CUSDT-PERP', 'tickSize': 2.5e-06},
            {'symbol': 'CVC-PERP', 'tickSize': 5e-05},
            {'symbol': 'CVX-PERP', 'tickSize': 0.0025},
            {'symbol': 'DASH-PERP', 'tickSize': 0.025},
            {'symbol': 'DAWN-PERP', 'tickSize': 0.0005},
            {'symbol': 'DEFI-PERP', 'tickSize': 0.1},
            {'symbol': 'DENT-PERP', 'tickSize': 1e-06},
            {'symbol': 'DODO-PERP', 'tickSize': 0.0005},
            {'symbol': 'DOGE-PERP', 'tickSize': 5e-07},
            {'symbol': 'DOT-PERP', 'tickSize': 0.001},
            {'symbol': 'DRGN-PERP', 'tickSize': 0.1},
            {'symbol': 'DYDX-PERP', 'tickSize': 0.001},
            {'symbol': 'EDEN-PERP', 'tickSize': 0.0005},
            {'symbol': 'EGLD-PERP', 'tickSize': 0.005},
            {'symbol': 'ENJ-PERP', 'tickSize': 5e-05},
            {'symbol': 'ENS-PERP', 'tickSize': 0.005},
            {'symbol': 'EOS-PERP', 'tickSize': 0.00025},
            {'symbol': 'ETC-PERP', 'tickSize': 0.0005},
            {'symbol': 'ETH-PERP', 'tickSize': 0.1},
            {'symbol': 'EXCH-PERP', 'tickSize': 0.1},
            {'symbol': 'FIDA-PERP', 'tickSize': 0.0001},
            {'symbol': 'FIL-PERP', 'tickSize': 0.005},
            {'symbol': 'FLM-PERP', 'tickSize': 0.0005},
            {'symbol': 'FLOW-PERP', 'tickSize': 0.005},
            {'symbol': 'FTM-PERP', 'tickSize': 5e-05},
            {'symbol': 'FTT-PERP', 'tickSize': 0.0005},
            {'symbol': 'FXS-PERP', 'tickSize': 0.0025},
            {'symbol': 'GALA-PERP', 'tickSize': 2.5e-05},
            {'symbol': 'GLMR-PERP', 'tickSize': 0.00025},
            {'symbol': 'GMT-PERP', 'tickSize': 5e-05},
            {'symbol': 'GRT-PERP', 'tickSize': 5e-05},
            {'symbol': 'HBAR-PERP', 'tickSize': 5e-05},
            {'symbol': 'HNT-PERP', 'tickSize': 0.0001},
            {'symbol': 'HOLY-PERP', 'tickSize': 0.0001},
            {'symbol': 'HOT-PERP', 'tickSize': 1e-06},
            {'symbol': 'HT-PERP', 'tickSize': 0.0005},
            {'symbol': 'HUM-PERP', 'tickSize': 2.5e-05},
            {'symbol': 'ICP-PERP', 'tickSize': 0.01},
            {'symbol': 'ICX-PERP', 'tickSize': 5e-05},
            {'symbol': 'IMX-PERP', 'tickSize': 0.00025},
            {'symbol': 'IOST-PERP', 'tickSize': 5e-06},
            {'symbol': 'IOTA-PERP', 'tickSize': 0.0001},
            {'symbol': 'JASMY-PERP', 'tickSize': 2.5e-06},
            {'symbol': 'KAVA-PERP', 'tickSize': 0.0005},
            {'symbol': 'KBTT-PERP', 'tickSize': 2.5e-07},
            {'symbol': 'KIN-PERP', 'tickSize': 1e-08},
            {'symbol': 'KNC-PERP', 'tickSize': 0.0001},
            {'symbol': 'KSHIB-PERP', 'tickSize': 1e-05},
            {'symbol': 'KSM-PERP', 'tickSize': 0.01},
            {'symbol': 'KSOS-PERP', 'tickSize': 5e-07},
            {'symbol': 'LEO-PERP', 'tickSize': 0.0001},
            {'symbol': 'LINA-PERP', 'tickSize': 5e-06},
            {'symbol': 'LINK-PERP', 'tickSize': 0.0005},
            {'symbol': 'LOOKS-PERP', 'tickSize': 0.00025},
            {'symbol': 'LRC-PERP', 'tickSize': 5e-05},
            {'symbol': 'LTC-PERP', 'tickSize': 0.01},
            {'symbol': 'LUNA-PERP', 'tickSize': 0.001},
            {'symbol': 'MANA-PERP', 'tickSize': 0.0001},
            {'symbol': 'MAPS-PERP', 'tickSize': 0.0001},
            {'symbol': 'MATIC-PERP', 'tickSize': 2.5e-06},
            {'symbol': 'MCB-PERP', 'tickSize': 0.005},
            {'symbol': 'MEDIA-PERP', 'tickSize': 0.1},
            {'symbol': 'MER-PERP', 'tickSize': 0.0001},
            {'symbol': 'MID-PERP', 'tickSize': 0.1},
            {'symbol': 'MINA-PERP', 'tickSize': 0.00025},
            {'symbol': 'MKR-PERP', 'tickSize': 0.5},
            {'symbol': 'MNGO-PERP', 'tickSize': 2.5e-05},
            {'symbol': 'MOB-PERP', 'tickSize': 0.0005},
            {'symbol': 'MTA-PERP', 'tickSize': 0.0005},
            {'symbol': 'MTL-PERP', 'tickSize': 0.0005},
            {'symbol': 'MVDA10-PERP', 'tickSize': 2.5},
            {'symbol': 'MVDA25-PERP', 'tickSize': 2.5},
            {'symbol': 'NEAR-PERP', 'tickSize': 0.0005},
            {'symbol': 'NEO-PERP', 'tickSize': 0.0025},
            {'symbol': 'OKB-PERP', 'tickSize': 0.0005},
            {'symbol': 'OMG-PERP', 'tickSize': 0.0005},
            {'symbol': 'ONE-PERP', 'tickSize': 2.5e-05},
            {'symbol': 'ONT-PERP', 'tickSize': 5e-05},
            {'symbol': 'ORBS-PERP', 'tickSize': 2.5e-05},
            {'symbol': 'OXY-PERP', 'tickSize': 0.0005},
            {'symbol': 'PAXG-PERP', 'tickSize': 0.1},
            {'symbol': 'PEOPLE-PERP', 'tickSize': 1e-05},
            {'symbol': 'PERP-PERP', 'tickSize': 0.001},
            {'symbol': 'POLIS-PERP', 'tickSize': 2.5e-05},
            {'symbol': 'PRIV-PERP', 'tickSize': 0.1},
            {'symbol': 'PROM-PERP', 'tickSize': 0.005},
            {'symbol': 'PUNDIX-PERP', 'tickSize': 0.0005},
            {'symbol': 'QTUM-PERP', 'tickSize': 0.001},
            {'symbol': 'RAMP-PERP', 'tickSize': 0.0001},
            {'symbol': 'RAY-PERP', 'tickSize': 0.0001},
            {'symbol': 'REEF-PERP', 'tickSize': 5e-06},
            {'symbol': 'REN-PERP', 'tickSize': 5e-05},
            {'symbol': 'RNDR-PERP', 'tickSize': 0.0005},
            {'symbol': 'RON-PERP', 'tickSize': 0.0005},
            {'symbol': 'ROOK-PERP', 'tickSize': 0.05},
            {'symbol': 'ROSE-PERP', 'tickSize': 5e-05},
            {'symbol': 'RSR-PERP', 'tickSize': 5e-06},
            {'symbol': 'RUNE-PERP', 'tickSize': 0.0005},
            {'symbol': 'SAND-PERP', 'tickSize': 5e-05},
            {'symbol': 'SC-PERP', 'tickSize': 2.5e-06},
            {'symbol': 'SCRT-PERP', 'tickSize': 5e-05},
            {'symbol': 'SECO-PERP', 'tickSize': 0.0001},
            {'symbol': 'SHIB-PERP', 'tickSize': 1e-08},
            {'symbol': 'SHIT-PERP', 'tickSize': 0.1},
            {'symbol': 'SKL-PERP', 'tickSize': 0.0001},
            {'symbol': 'SLP-PERP', 'tickSize': 2.5e-05},
            {'symbol': 'SNX-PERP', 'tickSize': 0.0005},
            {'symbol': 'SOL-PERP', 'tickSize': 0.0025},
            {'symbol': 'SOS-PERP', 'tickSize': 1e-08},
            {'symbol': 'SPELL-PERP', 'tickSize': 2.5e-06},
            {'symbol': 'SRM-PERP', 'tickSize': 0.001},
            {'symbol': 'SRN-PERP', 'tickSize': 5e-06},
            {'symbol': 'STEP-PERP', 'tickSize': 0.0005},
            {'symbol': 'STMX-PERP', 'tickSize': 5e-06},
            {'symbol': 'STORJ-PERP', 'tickSize': 0.0005},
            {'symbol': 'STX-PERP', 'tickSize': 0.00025},
            {'symbol': 'SUSHI-PERP', 'tickSize': 0.0001},
            {'symbol': 'SXP-PERP', 'tickSize': 0.0005},
            {'symbol': 'THETA-PERP', 'tickSize': 5e-05},
            {'symbol': 'TLM-PERP', 'tickSize': 5e-05},
            {'symbol': 'TOMO-PERP', 'tickSize': 5e-05},
            {'symbol': 'TONCOIN-PERP', 'tickSize': 0.0005},
            {'symbol': 'TRU-PERP', 'tickSize': 2.5e-05},
            {'symbol': 'TRX-PERP', 'tickSize': 2.5e-06},
            {'symbol': 'TRYB-PERP', 'tickSize': 1e-05},
            {'symbol': 'TULIP-PERP', 'tickSize': 0.0025},
            {'symbol': 'UNI-PERP', 'tickSize': 0.001},
            {'symbol': 'UNISWAP-PERP', 'tickSize': 25.0},
            {'symbol': 'USDT-PERP', 'tickSize': 0.0001},
            {'symbol': 'UST-PERP', 'tickSize': 0.0001},
            {'symbol': 'VET-PERP', 'tickSize': 5e-06},
            {'symbol': 'WAVES-PERP', 'tickSize': 0.0005},
            {'symbol': 'XAUT-PERP', 'tickSize': 0.1},
            {'symbol': 'XEM-PERP', 'tickSize': 5e-05},
            {'symbol': 'XLM-PERP', 'tickSize': 2.5e-05},
            {'symbol': 'XMR-PERP', 'tickSize': 0.01},
            {'symbol': 'XRP-PERP', 'tickSize': 2.5e-05},
            {'symbol': 'XTZ-PERP', 'tickSize': 0.0001},
            {'symbol': 'YFI-PERP', 'tickSize': 5.0},
            {'symbol': 'YFII-PERP', 'tickSize': 0.25},
            {'symbol': 'ZEC-PERP', 'tickSize': 0.01},
            {'symbol': 'ZIL-PERP', 'tickSize': 1e-05},
            {'symbol': 'ZRX-PERP', 'tickSize': 0.00025}
        ])

        this._lookup.set('Mango',[
            {'symbol': 'MNGO-PERP', 'tickSize': 0.0001},
            {'symbol': 'BTC-PERP', 'tickSize': 0.1},
            {'symbol': 'ETH-PERP', 'tickSize': 0.1},
            {'symbol': 'SOL-PERP', 'tickSize': 0.01},
            {'symbol': 'SRM-PERP', 'tickSize': 0.001},
            {'symbol': 'RAY-PERP', 'tickSize': 0.001},
            {'symbol': 'FTT-PERP', 'tickSize': 0.001},
            {'symbol': 'ADA-PERP', 'tickSize': 0.0001},
            {'symbol': 'BNB-PERP', 'tickSize': 0.1},
            {'symbol': 'AVAX-PERP', 'tickSize': 0.01},
            {'symbol': 'LUNA-PERP', 'tickSize': 0.01}
        ])

        this._lookup.set('BitMEX',[
            {'symbol': 'XBTUSD', 'tickSize': 0.5, 'symbolIndex': 88},
            {'symbol': 'ETHUSD', 'tickSize': 0.05, 'symbolIndex': 297},
            {'symbol': 'XRPUSD', 'tickSize': 0.0001, 'symbolIndex': 377},
            {'symbol': 'BCHUSD', 'tickSize': 0.05, 'symbolIndex': 402},
            {'symbol': 'LTCUSD', 'tickSize': 0.01, 'symbolIndex': 407},
            {'symbol': 'LINKUSDT', 'tickSize': 0.001, 'symbolIndex': 441},
            {'symbol': 'DOGEUSDT', 'tickSize': 1e-05, 'symbolIndex': 476},
            {'symbol': 'DOTUSDT', 'tickSize': 0.001, 'symbolIndex': 519},
            {'symbol': 'ADAUSDT', 'tickSize': 0.0001, 'symbolIndex': 521},
            {'symbol': 'EOSUSDT', 'tickSize': 0.0001, 'symbolIndex': 539},
            {'symbol': 'BNBUSDT', 'tickSize': 0.01, 'symbolIndex': 542},
            {'symbol': 'SOLUSDT', 'tickSize': 0.01, 'symbolIndex': 549},
            {'symbol': 'XBTEUR', 'tickSize': 0.5, 'symbolIndex': 564},
            {'symbol': 'MATICUSDT', 'tickSize': 0.0001, 'symbolIndex': 588},
            {'symbol': 'LUNAUSD', 'tickSize': 0.001, 'symbolIndex': 649},
            {'symbol': 'AVAXUSD', 'tickSize': 0.001, 'symbolIndex': 675},
            {'symbol': 'ADAUSD', 'tickSize': 0.0001, 'symbolIndex': 676},
            {'symbol': 'DOGEUSD', 'tickSize': 1e-05, 'symbolIndex': 677},
            {'symbol': 'BNBUSD', 'tickSize': 0.01, 'symbolIndex': 678},
            {'symbol': 'DOTUSD', 'tickSize': 0.001, 'symbolIndex': 679},
            {'symbol': 'AXSUSD', 'tickSize': 0.01, 'symbolIndex': 706},
            {'symbol': 'EOSUSD', 'tickSize': 0.0001, 'symbolIndex': 707},
            {'symbol': 'LINKUSD', 'tickSize': 0.001, 'symbolIndex': 708},
            {'symbol': 'SOLUSD', 'tickSize': 0.01, 'symbolIndex': 709},
            {'symbol': 'XBTUSDT', 'tickSize': 0.5, 'symbolIndex': 732},
            {'symbol': 'ETHUSDT', 'tickSize': 0.05, 'symbolIndex': 734},
            {'symbol': 'XRPUSDT', 'tickSize': 0.0001, 'symbolIndex': 736},
            {'symbol': 'BCHUSDT', 'tickSize': 0.05, 'symbolIndex': 737},
            {'symbol': 'LTCUSDT', 'tickSize': 0.01, 'symbolIndex': 738},
            {'symbol': 'SHIBUSDT', 'tickSize': 1e-09, 'symbolIndex': 754},
            {'symbol': 'FTMUSDT', 'tickSize': 0.0001, 'symbolIndex': 755},
            {'symbol': 'SANDUSDT', 'tickSize': 0.0001, 'symbolIndex': 780},
            {'symbol': 'MANAUSDT', 'tickSize': 0.0001, 'symbolIndex': 781},
            {'symbol': 'ALTMEXTUSDT', 'tickSize': 0.01, 'symbolIndex': 801},
            {'symbol': 'DEFIMEXTUSDT', 'tickSize': 0.01, 'symbolIndex': 802},
            {'symbol': 'METAMEXTUSDT', 'tickSize': 0.01, 'symbolIndex': 803},
            {'symbol': 'AVAXUSDT', 'tickSize': 0.001, 'symbolIndex': 808},
            {'symbol': 'LUNAUSDT', 'tickSize': 0.001, 'symbolIndex': 809},
            {'symbol': 'APEUSDT', 'tickSize': 0.001, 'symbolIndex': 826}
        ])

        this._lookup.set('Binance',[
            {'symbol': 'BTCUSDT', 'tickSize': 0.1},
            {'symbol': 'ETHUSDT', 'tickSize': 0.01},
            {'symbol': 'BCHUSDT', 'tickSize': 0.01},
            {'symbol': 'XRPUSDT', 'tickSize': 0.0001},
            {'symbol': 'EOSUSDT', 'tickSize': 0.001},
            {'symbol': 'LTCUSDT', 'tickSize': 0.01},
            {'symbol': 'TRXUSDT', 'tickSize': 1e-05},
            {'symbol': 'ETCUSDT', 'tickSize': 0.001},
            {'symbol': 'LINKUSDT', 'tickSize': 0.001},
            {'symbol': 'XLMUSDT', 'tickSize': 1e-05},
            {'symbol': 'ADAUSDT', 'tickSize': 0.0001},
            {'symbol': 'XMRUSDT', 'tickSize': 0.01},
            {'symbol': 'DASHUSDT', 'tickSize': 0.01},
            {'symbol': 'ZECUSDT', 'tickSize': 0.01},
            {'symbol': 'XTZUSDT', 'tickSize': 0.001},
            {'symbol': 'BNBUSDT', 'tickSize': 0.01},
            {'symbol': 'ATOMUSDT', 'tickSize': 0.001},
            {'symbol': 'ONTUSDT', 'tickSize': 0.0001},
            {'symbol': 'IOTAUSDT', 'tickSize': 0.0001},
            {'symbol': 'BATUSDT', 'tickSize': 0.0001},
            {'symbol': 'VETUSDT', 'tickSize': 1e-05},
            {'symbol': 'NEOUSDT', 'tickSize': 0.001},
            {'symbol': 'QTUMUSDT', 'tickSize': 0.001},
            {'symbol': 'IOSTUSDT', 'tickSize': 1e-06},
            {'symbol': 'THETAUSDT', 'tickSize': 0.001},
            {'symbol': 'ALGOUSDT', 'tickSize': 0.0001},
            {'symbol': 'ZILUSDT', 'tickSize': 1e-05},
            {'symbol': 'KNCUSDT', 'tickSize': 0.001},
            {'symbol': 'ZRXUSDT', 'tickSize': 0.0001},
            {'symbol': 'COMPUSDT', 'tickSize': 0.01},
            {'symbol': 'OMGUSDT', 'tickSize': 0.001},
            {'symbol': 'DOGEUSDT', 'tickSize': 1e-05},
            {'symbol': 'SXPUSDT', 'tickSize': 0.0001},
            {'symbol': 'KAVAUSDT', 'tickSize': 0.0001},
            {'symbol': 'BANDUSDT', 'tickSize': 0.0001},
            {'symbol': 'RLCUSDT', 'tickSize': 0.0001},
            {'symbol': 'WAVESUSDT', 'tickSize': 0.001},
            {'symbol': 'MKRUSDT', 'tickSize': 0.1},
            {'symbol': 'SNXUSDT', 'tickSize': 0.001},
            {'symbol': 'DOTUSDT', 'tickSize': 0.001},
            {'symbol': 'DEFIUSDT', 'tickSize': 0.1},
            {'symbol': 'YFIUSDT', 'tickSize': 1.0},
            {'symbol': 'BALUSDT', 'tickSize': 0.001},
            {'symbol': 'CRVUSDT', 'tickSize': 0.001},
            {'symbol': 'TRBUSDT', 'tickSize': 0.01},
            {'symbol': 'YFIIUSDT', 'tickSize': 0.1},
            {'symbol': 'RUNEUSDT', 'tickSize': 0.001},
            {'symbol': 'SUSHIUSDT', 'tickSize': 0.001},
            {'symbol': 'SRMUSDT', 'tickSize': 0.001},
            {'symbol': 'EGLDUSDT', 'tickSize': 0.01},
            {'symbol': 'SOLUSDT', 'tickSize': 0.01},
            {'symbol': 'ICXUSDT', 'tickSize': 0.0001},
            {'symbol': 'STORJUSDT', 'tickSize': 0.0001},
            {'symbol': 'BLZUSDT', 'tickSize': 1e-05},
            {'symbol': 'UNIUSDT', 'tickSize': 0.001},
            {'symbol': 'AVAXUSDT', 'tickSize': 0.01},
            {'symbol': 'FTMUSDT', 'tickSize': 0.0001},
            {'symbol': 'HNTUSDT', 'tickSize': 0.001},
            {'symbol': 'ENJUSDT', 'tickSize': 0.0001},
            {'symbol': 'FLMUSDT', 'tickSize': 0.0001},
            {'symbol': 'TOMOUSDT', 'tickSize': 0.0001},
            {'symbol': 'RENUSDT', 'tickSize': 0.0001},
            {'symbol': 'KSMUSDT', 'tickSize': 0.01},
            {'symbol': 'NEARUSDT', 'tickSize': 0.001},
            {'symbol': 'AAVEUSDT', 'tickSize': 0.01},
            {'symbol': 'FILUSDT', 'tickSize': 0.001},
            {'symbol': 'RSRUSDT', 'tickSize': 1e-06},
            {'symbol': 'LRCUSDT', 'tickSize': 0.0001},
            {'symbol': 'MATICUSDT', 'tickSize': 0.0001},
            {'symbol': 'OCEANUSDT', 'tickSize': 1e-05},
            {'symbol': 'CVCUSDT', 'tickSize': 1e-05},
            {'symbol': 'BELUSDT', 'tickSize': 0.0001},
            {'symbol': 'CTKUSDT', 'tickSize': 0.001},
            {'symbol': 'AXSUSDT', 'tickSize': 0.01},
            {'symbol': 'ALPHAUSDT', 'tickSize': 0.0001},
            {'symbol': 'ZENUSDT', 'tickSize': 0.001},
            {'symbol': 'SKLUSDT', 'tickSize': 1e-05},
            {'symbol': 'GRTUSDT', 'tickSize': 1e-05},
            {'symbol': '1INCHUSDT', 'tickSize': 0.0001},
            {'symbol': 'BTCBUSD', 'tickSize': 0.1},
            {'symbol': 'AKROUSDT', 'tickSize': 1e-05},
            {'symbol': 'CHZUSDT', 'tickSize': 1e-05},
            {'symbol': 'SANDUSDT', 'tickSize': 0.0001},
            {'symbol': 'ANKRUSDT', 'tickSize': 1e-05},
            {'symbol': 'LUNAUSDT', 'tickSize': 0.001},
            {'symbol': 'BTSUSDT', 'tickSize': 1e-05},
            {'symbol': 'LITUSDT', 'tickSize': 0.001},
            {'symbol': 'UNFIUSDT', 'tickSize': 0.001},
            {'symbol': 'DODOUSDT', 'tickSize': 0.001},
            {'symbol': 'REEFUSDT', 'tickSize': 1e-06},
            {'symbol': 'RVNUSDT', 'tickSize': 1e-05},
            {'symbol': 'SFPUSDT', 'tickSize': 0.0001},
            {'symbol': 'XEMUSDT', 'tickSize': 0.0001},
            {'symbol': 'BTCSTUSDT', 'tickSize': 0.001},
            {'symbol': 'COTIUSDT', 'tickSize': 1e-05},
            {'symbol': 'CHRUSDT', 'tickSize': 0.0001},
            {'symbol': 'MANAUSDT', 'tickSize': 0.0001},
            {'symbol': 'ALICEUSDT', 'tickSize': 0.001},
            {'symbol': 'HBARUSDT', 'tickSize': 1e-05},
            {'symbol': 'ONEUSDT', 'tickSize': 1e-05},
            {'symbol': 'LINAUSDT', 'tickSize': 1e-05},
            {'symbol': 'STMXUSDT', 'tickSize': 1e-05},
            {'symbol': 'DENTUSDT', 'tickSize': 1e-06},
            {'symbol': 'CELRUSDT', 'tickSize': 1e-05},
            {'symbol': 'HOTUSDT', 'tickSize': 1e-06},
            {'symbol': 'MTLUSDT', 'tickSize': 0.0001},
            {'symbol': 'OGNUSDT', 'tickSize': 0.0001},
            {'symbol': 'NKNUSDT', 'tickSize': 1e-05},
            {'symbol': 'SCUSDT', 'tickSize': 1e-06},
            {'symbol': 'DGBUSDT', 'tickSize': 1e-05},
            {'symbol': '1000SHIBUSDT', 'tickSize': 1e-06},
            {'symbol': 'ICPUSDT', 'tickSize': 0.01},
            {'symbol': 'BAKEUSDT', 'tickSize': 0.0001},
            {'symbol': 'GTCUSDT', 'tickSize': 0.001},
            {'symbol': 'ETHBUSD', 'tickSize': 0.01},
            {'symbol': 'BTCDOMUSDT', 'tickSize': 0.1},
            {'symbol': 'TLMUSDT', 'tickSize': 0.0001},
            {'symbol': 'BNBBUSD', 'tickSize': 0.01},
            {'symbol': 'ADABUSD', 'tickSize': 0.0001},
            {'symbol': 'XRPBUSD', 'tickSize': 0.0001},
            {'symbol': 'IOTXUSDT', 'tickSize': 1e-05},
            {'symbol': 'DOGEBUSD', 'tickSize': 1e-05},
            {'symbol': 'AUDIOUSDT', 'tickSize': 0.0001},
            {'symbol': 'RAYUSDT', 'tickSize': 0.001},
            {'symbol': 'C98USDT', 'tickSize': 0.0001},
            {'symbol': 'MASKUSDT', 'tickSize': 0.001},
            {'symbol': 'ATAUSDT', 'tickSize': 0.0001},
            {'symbol': 'SOLBUSD', 'tickSize': 0.01},
            {'symbol': 'FTTBUSD', 'tickSize': 0.001},
            {'symbol': 'DYDXUSDT', 'tickSize': 0.001},
            {'symbol': '1000XECUSDT', 'tickSize': 1e-05},
            {'symbol': 'GALAUSDT', 'tickSize': 1e-05},
            {'symbol': 'CELOUSDT', 'tickSize': 0.001},
            {'symbol': 'ARUSDT', 'tickSize': 0.001},
            {'symbol': 'KLAYUSDT', 'tickSize': 0.0001},
            {'symbol': 'ARPAUSDT', 'tickSize': 1e-05},
            {'symbol': 'CTSIUSDT', 'tickSize': 0.0001},
            {'symbol': 'LPTUSDT', 'tickSize': 0.001},
            {'symbol': 'ENSUSDT', 'tickSize': 0.001},
            {'symbol': 'PEOPLEUSDT', 'tickSize': 1e-05},
            {'symbol': 'ANTUSDT', 'tickSize': 0.001},
            {'symbol': 'ROSEUSDT', 'tickSize': 1e-05},
            {'symbol': 'DUSKUSDT', 'tickSize': 1e-05},
            {'symbol': '1000BTTCUSDT', 'tickSize': 1e-06},
            {'symbol': 'FLOWUSDT', 'tickSize': 0.001},
            {'symbol': 'IMXUSDT', 'tickSize': 0.0001},
            {'symbol': 'API3USDT', 'tickSize': 0.001},
            {'symbol': 'ANCUSDT', 'tickSize': 0.001},
            {'symbol': 'GMTUSDT', 'tickSize': 1e-05},
            {'symbol': 'APEUSDT', 'tickSize': 0.001},
            {'symbol': 'BNXUSDT', 'tickSize': 0.01}
        ])
    }

    getExchanges(): string[] {
        return [...this._lookup.keys()]
    }

    getExchangeInstruments(exchange: string): Instrument[] {
        return this._lookup.get(exchange)!
    }

    getExchangeInstrument(exchange: string, symbol: string): Instrument {
        const symbols = this.getExchangeInstruments(exchange)
        return symbols.find((ins: Instrument) => ins.symbol === symbol)!
    }
}